apiVersion: v1
kind: PersistentVolume
metadata:
  name: minikube-demo-local-persistentvolume
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"