apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: minikube-demo-server-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: minikube-demo-server-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10