apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minikube-demo-local-persistentvolume-claim
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi